---
ansible_user: centos
ansible_password: "{{ vault_ansible_password }}"

# defaults file for roles
system_user: cloud_user
compose_project_dir: /home/{{ system_user }}/site-vitrine/wordpress-backup

db_container_name: site-vitrine-db
db_volume_name: site-vitrine-db-data
wordpress_container_name: site-vitrine-web
phpmyadmin_container_name: site-vitrine-phpmyadmin
wordpress_site: /home/{{ system_user }}/site-vitrine/eazytraining

wp_db_user: eazytraining
wp_db_psw: nrAZ9xOHnypowWm99cHL
db_root_psw: 32c2398576db06e84a9fd6eec1de9be1
wp_db_name: eazytraining

wp_version: 6.4.2
wordpress_webroot: /var/www/html
wordpress_site_url: https://eazytraining.fr

site_vitrine_directory: "/home/{{ system_user }}/site-vitrine"
group_gid: tape

wordpress_title: wordpress
wordpress_admin_user: Aurelie
wordpress_admin_password: 1234
wordpress_admin_email: nkblondelle@gmail.com

init_script: /home/{{ system_user }}/init.sh

# access key and secret key to access in bucket s3
backup_db_dir: "global_backup_db"

#name and region of bucket to backup on s3
s3_bucket_name: "backup-semaphore"
region: "us-east-1"

# db backup folder backup
global_backup_db: "{{ compose_project_dir }}/global_backup_db"
s3_remote_directory_db: "global_backup_db"

# global plugins folder backup
global_backup_plugins: "{{ compose_project_dir }}/global_backup_plugins"
s3_remote_directory_plugins: "global_backup_plugins"

# global themes folder backup
global_backup_themes: "{{ compose_project_dir }}/global_backup_themes"
s3_remote_directory_themes: "global_backup_themes"

# specific plugins folder backup
specific_backup_plugins: "{{ compose_project_dir }}/specific_backup_plugins/"
s3_remote_directory_specific_plugins: "specific_backup_plugins"

# specific themes folder backup
specific_backup_themes: "{{ compose_project_dir }}/specific_backup_themes/"
s3_remote_directory_specific_themes: "specific_backup_themes"

# site folder backup
global_backup_site: "{{ compose_project_dir }}/global_backup_site/"
s3_remote_directory_site: "global_backup_site"

# plugins_to_install
plugins_to_install:
  - akismet
  - malcare-security
  - w3-total-cache
  - redis-cache
  - learnpress

# plugins_to_activate
plugins_to_activate:
  - akismet
  - w3-total-cache
  - redis-cache

# plugins_to_uninstall
plugins_to_uninstall:
  - redis-cache
  # - //**/ hello commntaire
  #sdfsdfsdfsdf

# plugins_to_desactivate
plugins_to_deactivate:
  - w3-total-cache
  - redis-cache

# themes_to_install
themes_to_install:
  - medazin
  - ona
  - content
  - oceanwp

# themes_to_activate
themes_to_activate:
 - twentytwenty

# themes_to_uinstall
themes_to_uninstall:
  - medazin
  - ona
  - content
  - oceanwp
  - medazin
  # Ajoutez d'autres thèmes à désinstaller ici si nécessaire

new_theme_to_activate: twentytwentyfour # lorsqu'on voudra désactiver un théme faudra spécifier le nouveau thème à activer

# plugin_to_update
plugin_to_update:
  plugin_name: "learnpress"
  new_version: 4.2.6.2

# theme_to_update
theme_to_update:
  theme_name: "twentytwenty"
  new_version: 2.5

# restore_db_name locally
restore_db_name:
  restore_pattern: "backup_2024-03-12-105133Z_EAZYTraining_X1R4PR8pyq_global_db.sql"
  restore_files_path: "{{ compose_project_dir }}/global_backup_db"

# restore_db_name in bucket s3
s3_filename_db: "backup_2024-03-12-105133Z_EAZYTraining_X1R4PR8pyq_global_db.sql"
s3_restore_db_name:
  restore_pattern: "backup_2024-03-12-105133Z_EAZYTraining_X1R4PR8pyq_global_db.sql"
  restore_files_path: "{{ compose_project_dir }}/s3_db_restore"

# restore_file_name
restore_file_name:
  restore_pattern: "backup_2024-03-07-020013Z_EAZYTraining_aEdpNcgYtB_global.zip"
  restore_files_path: "{{ compose_project_dir }}/global_backup_site"

# restore_plugins_name
restore_plugins_name:
  restore_pattern: "*"
  restore_files_path: "{{ compose_project_dir }}/global_backup_plugins/backup_2024-01-28-210350Z_EAZYTraining_1UrInA84kU_plugins"

# restore_plugins_name
restore_themes_name:
  restore_pattern: "*"
  restore_files_path: "{{ compose_project_dir }}/global_backup_themes/backup_2024-01-28-210530Z_EAZYTraining_n3wamfG3qu_themes"

# restore_themes_name
s3_global_theme_restore: "{{ compose_project_dir }}/s3_global_theme_restore"
s3_filename_themes: "backup_2024-01-28-210530Z_EAZYTraining_n3wamfG3qu_themes"
s3_restore_themes_name:
  restore_pattern: "*"
  restore_files_path: "{{ compose_project_dir }}/s3_global_theme_restore/backup_2024-01-28-210530Z_EAZYTraining_n3wamfG3qu_themes/"

# specific_plugin_name_restore local
specific_plugin_name_restore:
  restore_pattern: "backup_2024-01-28-205255Z_EAZYTraining_IyaShGW7M2_malcare-security_5.41.zip"
  restore_files_path: "{{ compose_project_dir }}/specific_backup_plugins"

# specific_theme_name_restore local
specific_theme_name_restore:
  restore_pattern: "backup_2024-01-28-205852Z_EAZYTraining_XF7PYwzOtD_twentytwenty_1.1.zip"
  restore_files_path: "{{ compose_project_dir }}/specific_backup_themes"

# specific_plugin_name_restore in bucket s3
s3_filename_specific_plugins: "backup_2024-02-21-112913Z_EAZYTraining_0lUanfVoVu_page-scroll-to-id_1.7.8.zip"
s3_specific_plugin_name_restore:
  restore_pattern: "backup_2024-02-21-112913Z_EAZYTraining_0lUanfVoVu_page-scroll-to-id_1.7.8.zip"
  restore_files_path: "{{ compose_project_dir }}/s3_specific_plugin_restore"

# specific_theme_name_restore in bucket s3
s3_filename_specific_themes: "backup_2024-01-28-205852Z_EAZYTraining_XF7PYwzOtD_twentytwenty_1.1.zip"
s3_specific_theme_name_restore:
  restore_pattern: "backup_2024-01-28-205852Z_EAZYTraining_XF7PYwzOtD_twentytwenty_1.1.zip"
  restore_files_path: "{{ compose_project_dir }}/s3_specific_theme_restore"

# restore_file_name
s3_filename_site: "backup_2024-03-12-105133Z_EAZYTraining_awTUf330fb_global.zip"
s3_restore_file_name:
  restore_pattern: "backup_2024-03-12-105133Z_EAZYTraining_awTUf330fb_global.zip"
  restore_files_path: "{{ compose_project_dir }}/global_backup_site"

# restore_plugins_name
s3_global_plugin_restore: "{{ compose_project_dir }}/s3_global_plugin_restore"
s3_filename_plugins: "backup_2024-01-28-210350Z_EAZYTraining_1UrInA84kU_plugins"
s3_restore_plugins_name:
  restore_pattern: "*"
  restore_files_path: "{{ compose_project_dir }}/s3_global_plugin_restore/backup_2024-01-28-210350Z_EAZYTraining_1UrInA84kU_plugins"
